### ISSUE TITLE
🎉🎉信管工作室2018级后台寒假作业

### ISSUE THREAD

**Issue by GeniusDSY** [GeniusDSY/Winter-Vacation-Homework#2]
🚀🚀上大学的第一个寒假，给大家布置一些寒假作业，之前收集了大家喜欢的东西，那我们就去做一些大家喜欢的东西😄😄下面就是大家期待已久的作业了 😙😙

首先是一些寒假必须要去完成的事：

:one: 学会使用Git！掌握常用的基础命令的使用.

:two: 搭建一个属于自己的博客，可以搭建一个网站也可以写在Github的一个仓库里存放，但是也要学会使用markdown语法。可以把自己读书是的笔记或者一个复杂问题的解决写为博客。积累也是很重要的。

下面三项是根据之前你们培训的内容以及你们未来要去掌握的内容布置的三项任务，大家任选一项完成，自己建一个Github仓库托管代码，commit在这个issue里，只放链接即可。:star2:

如果有兴趣可以去了解一下 Github Pages 来搭建成一个可在线预览的仓库。:package:

提交格式:

姓名 + 选择题目 + 仓库链接 + [GitHub Pages 地址]

也祝大家过一个丰富快乐的新年！:fireworks:

[Hexo + Github Pages 搭建个人博客](https://www.jianshu.com/p/2b09156ee5b1)

[git 教程](https://www.liaoxuefeng.com/wiki/0013739516305929606dd18361248578c67b8067c8c017b000/)

🏷 One :    Mis论坛

:实现功能：

- 登陆注册
- 首页
  - 实现几条帖子的展示（点标题可以进入详情页那种）
    例如：
    ![](https://user-gold-cdn.xitu.io/2019/1/8/1682b2cb12bb221d?w=674&h=316&f=png&s=46718)    
  - 对帖子进行分类（点类别可以进入此分类的专题）
    例如：
    ![](https://user-gold-cdn.xitu.io/2019/1/8/1682b2c061077ea3?w=130&h=133&f=png&s=4561)
  - 最新问题的提出（点进去可以回答问题）

- 发表帖子
  - 帖子需要标明发布人，发布时间
  - 可以评论任意帖子（标明评论人）
- 用户主页
  - 实现个人资料的展示和更改（包括密码）
  - 历史帖子的展示、删除

- 加分项 
  - 实现对帖子以及评论的点赞以及楼中楼评论
  - 帖子的访问量展示，并根据访问量进行首页热帖榜展示（将前面实现的几条帖子的展示变成热帖的展示）
  - 个人头像的上传、更改以及展示
  - 用户之间可以点关注。并在关注好友有帖子发出后，进行消息提示

注：以上内容均可以参照新浪微博、百度贴吧、天涯论坛进行仿制

---

🏷 Two:    Mis ChatRoom

实现功能：

- 登陆注册
- 添加、删除好友
- 单聊
  - 展示双方名字
  - 发送消息的时间
- 拉讨论组，群聊
  - 显示发送消息人的名称以及消息发送的时间
- 加分项
  - 头像上传并在聊天中展示
  - 讨论组权限的管理（群主、管理员等）

注：以上内容可以仿QQ、WeChat等；可以选择实现客户端或者网页版（推荐）

---

🏷🏷Three:    

随意发挥！！！但是要根据上面的两个进行自己的发挥！！！慎选

---

😈  Last but not least:

技术选型：

- 框架：
  - Spring + Spring mvc + MyBatis
  - SpringBoot
  - Jsp + Servlet (尽量不使用这个)
- 数据库：
  - MySql
  - SqlYng（可视化工具）
- 服务器：
  - Apache TomCat(推荐使用8)
- 页面自己撸：
  - HTML + CSS ：https://www.imooc.com/learn/9
  - JAVAScript ：https://www.imooc.com/learn/36
    		       https://www.imooc.com/learn/10
    Ajax：		https://www.imooc.com/learn/250
- 再说几点需要注意的：
  - 页面不需要很好看，主要看功能
  - 不要去Copy，看得出来的（可以去模仿）
  - 大家加油

---

大家冲鸭🦆！！！

**Comment by GeniusDSY** [comment]
作业提交方式：
   1、自己在GitHub建一个寒假作业的仓库
   2、完成作业后，将自己的仓库链接评论到下面

**Comment by xiamiaocheng** [comment]
夏苗程+mis论坛+https://github.com/xiamiaocheng/xia.git

**Comment by xiuda3411** [comment]
宋丽+mis论坛+https://github.com/xiuda3411/MisForum

**Comment by bunnsisDreamer** [comment]
王增益 Mis论坛 https://github.com/bunnsisDreamer/homework.git

**Comment by GCSylvia** [comment]
王坤 +https://github.com/GCSylvia/GCSylvia.github.io（没有做出论坛或者chat room的小白只能交出一个粗略的blog...）

**Comment by hansyyy** [comment]
韩思玥 Mis论坛 https://github.com/hansyyy/WebProject1

**Comment by NightMid** [comment]
余文平+ChatRoom+https://github.com/NightMid/-Chatroom.git
博客https://NightMid.github.io/（待优化）

**Comment by NightMid** [comment]
余文平+ChatRoom+https://github.com/NightMid/-Chatroom.git
博客：https://nightmid.github.io/       （待优化）

**Comment by Yueyuyu** [comment]
杨兴旺+Mis ChatRoom+https://github.com/Yueyuyu/Winter-vacation-operation
blog：https://yueyuyu.github.io/

**Comment by LeeKonyu** [comment]
李康语
博客：https://leekonyu.github.io/
论坛：https://github.com/LeeKonyu/test/tree/master/ssmdemo

**Comment by Preciousone** [comment]
粟振华
博客：https://preciousone.github.io/
论坛：https://github.com/Preciousone/firework.github.io/

**Comment by spx0315** [comment]
孙鹏翔
聊天室：https://github.com/spx0315/WebChat.git
坦克大战（聊天室实在不会最后一天赶了一个坦克大战，希望23:59之前能做好）：https://github.com/spx0315/Swing.git

**Comment by GeniusDSY** [comment]
我已经关闭了该issue，还想交作业的，QQ找我私聊
