### ISSUE TITLE
🎉🎉信管工作室2018级前端寒假作业

### ISSUE THREAD

**Issue by Reaper622** [GeniusDSY/Winter-Vacation-Homework#3]
# 前端寒假作业考核

Time flies！转眼间你们的大一已经过了一半了，我们的招新考核也已经到达了最后阶段！:smiley:

首先是一些寒假必须要去完成的事：

:one: 学会使用Git！掌握常用的基础命令的使用.

:two: 搭建一个属于自己的博客，可以搭建一个网站也可以写在Github的一个仓库里存放，但是也要学会使用markdown语法。可以把自己读书是的笔记或者一个复杂问题的解决写为博客。积累也是很重要的。

下面三项是根据之前你们培训的内容以及你们未来要去掌握的内容布置的三项任务，大家任选一项完成，自己建一个Github仓库托管代码，commit在这个issue里，只放链接即可。:star2:

如果有兴趣可以去了解一下 Github Pages 来搭建成一个可在线预览的仓库。:package:

提交格式:

姓名 + 选择题目 + 仓库链接 + [GitHub Pages 地址]

也祝大家过一个丰富快乐的新年！:fireworks:

[Hexo + Github Pages 搭建个人博客](https://www.jianshu.com/p/2b09156ee5b1)

[git 教程](https://www.liaoxuefeng.com/wiki/0013739516305929606dd18361248578c67b8067c8c017b000/)

### 主要功能

- 每页只显示一道题，做完一道之后切换下一道，十个题为一次答题。（可参考轮播）
- 题目的内容通过Ajax请求动态获得,题目为选择题，只有一个正确选项。
- 题目尽量与前端相关，也算是复习之前的知识。
- 接口自己写Mock模拟接口数据(Mock工具:[RAP2](http://rap2.taobao.org/) ,[EasyMock](https://www.easy-mock.com))
- 每道题依次对应不同的分数，每次答完十道题后将分数&答题时间一起存储本地。(参考localstorage)
- 排行榜功能，将历史获得的前五高的名词次展示。 
- 计时功能，每次答题时限一定，时间到自动算提交答卷。(也可以加入提醒功能:bell:)

### 要求

- 页面美观，基本但也不简单的要求。:smiley:
- 有主要功能展示—— 可以以截图+文字的格式写在git仓库的README中。
- 有文件描述——每个文件的相应功能写明确,写在git仓库的README中。
- 使用HTML5 + CSS3 + 原生Javascript 实现。
- Mock接口实在不会用找李博文要接口(不提倡!):no_good_man:

#### 这是豆瓣电影TOP250的接口：http://api.douban.com/v2/movie/top250

也就是你们的作业中电影数据的来源，如果有跨域的问题（接口无法访问）自己尝试解决，不会的找李俭奇换mock接口

### 主要功能

+ 将获得的电影数据（至少展示标题，分类，平均分，其他数据任意）分页展示，就是可以一页n条，可以点击前一页后一页那种。
+ 可以点击每一行的电影标题查看它的详情（比如它的海报图片，年份等）。
+ 每一行的尾部有一个按钮，可以进行收藏，把用户收藏的东西存在本地（localStorage），以后再次访问就会显示已经收藏，当然也可以取消收藏。
+ 可以查看自己收藏了哪些电影。
+ 增、删、改、查：四个功能尽可能去实现（不用发送请求，所以刷新页面后还是会恢复原样）。

### 要求

+ 使用GitHub进行代码托管。
+ 使用CSS把样式写好看一点。

### 主要功能

- 游戏的玩法介绍通过Ajax动态获得
- 接口自己写Mock模拟接口数据(Mock工具:[RAP2](http://rap2.taobao.org/) ,[EasyMock](https://www.easy-mock.com))
- 开始时棋盘内随机出现两个数字，出现的数字仅可能为2或4
- 按键盘 ↑ ↓ ← →对应不同的移动 
- 玩家选择的方向上若有相同的数字则合并，每次有效移动可以同时合并，但不可以连续合并
- 每有效移动一步，棋盘的空位(无数字处)随机出现一个数字(依然可能为2或4)
- 玩家选择的方向行或列前方有空格则出现位移
- 记录步骤 并在右侧实时展示，在结束时存入本地，实现排行榜（localstorage）
- 棋盘被数字填满，无法进行有效移动，判负，游戏结束
- 棋盘上出现2048，判胜，游戏结束
- 详细的规则就不细写了，不懂得可以Google or 百度。

样式大概为 [![Fo5SQe.jpg](https://s2.ax1x.com/2019/01/03/Fo5SQe.jpg)](https://imgchr.com/i/Fo5SQe)

### 要求

- 页面美观，基本但也不简单的要求。:smiley:
- 有主要功能展示—— 可以以截图+文字的格式写在git仓库的README中。
- 有文件描述——每个文件的相应功能写明确,写在git仓库的README中。
- 使用HTML5 + CSS3 + 原生Javascript 实现。
- 使用Github进行代码托管
- 响应式适配不同分辨率屏幕

功能点都尽可能去实现，Happy coding！

**Comment by Reaper622** [comment]
2月20日为最终截止时间，无论写完与否一定要Commit
否则默认为give up.:cry:
Do your best.

**Comment by renchongwei123** [comment]
任崇伟 
在线答题网站(网址  118.24.145.199/前端作业1)
电影收藏网站(网址  118.24.145.199/前端作业2)
仓库地址:https://github.com/renchongwei123/atelier-assignment
githubpage地址:renchongwei123/renchongwei123.github.io;

**Comment by woyasuohen6** [comment]
在线答题网站(网址: 118.24.145.199/前端作业1)
电影收藏网站(网址: 118.24.145.199/前端作业2)
仓库地址: https://github.com/woyasuohen6/atelier-assignment
githubpage地址: https://github.com/woyasuohen6/woyasuohen6.github.io

**Comment by Reaper622** [comment]
@woyasuohen6  试着把所有东西放在一个仓库的习惯更改一下，一个项目写在一个仓库里，第一个作业功能没有实现完全啊，Ajax请求还是有一定问题的，争取最近能够在完善一下。

**Comment by Qhappyman** [comment]
在线答题仓库https://github.com/Qhappyman/winterhomework
预览和介绍都在README.md里面

**Comment by EsperanceW** [comment]
姓名：王志豪
选择题目：在线答题网站
仓库链接：https://github.com/EsperanceW/homework
GitHub Pages地址：https://esperancew.github.io

**Comment by cool-liuchang** [comment]
姓名：刘畅
选择题目：2048小游戏
仓库链接：https://github.com/cool-liuchang/cool-liuchang.github.io
GitHub Pages地址：https://cool-liuchang.github.io

**Comment by AndreaCJY** [comment]
姓名：陈佳怡
选择题目：在线答题网站
仓库链接：https://github.com/AndreaCJY/neverland.git
GitHub Pages地址：https://github.com/AndreaCJY/AndreaCJY.github.io.git

**Comment by LIUYILINGXING** [comment]
姓名：刘怡伶
选择题目：2048
仓库链接：https://github.com/LIUYILINGXING/hello-world
GitHub Pages地址：https://github.com/LIUYILINGXING/LIUYILINGXING.github.io

**Comment by ETERNITYhwt** [comment]
姓名：韩汶婷
选择题目：在线答题网站
仓库链接https://github.com/ETERNITYhwt?tab=repositories
GitHub Pages地址：https://github.com/ETERNITYhwt/homework

**Comment by wsssswccc** [comment]
姓名：王沙沙
选择题目：在线答题网站
仓库链接：https://github.com/wsssswccc/hello-world
GitHub Page地址： https://wsssswccc.github.io/

**Comment by GAOLUYUE** [comment]
姓名：高璐玥
选择题目：2048
仓库链接：https://github.com/GAOLUYUE/zuoye
GitHub Pages地址：https://github.com/GAOLUYUE/lll.git.io
